spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: whyjhqlove512

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: Jovaunn1
      hikari:
        max-lifetime: 1765000
        maximum-pool-size: 10
  mail:
      host: smtp.qq.com  #smtp.ym.163.com[此处填你的邮箱服务地址]
      username: 1044038055@qq.com #[账号]
      password: aegwljmfdtzkbbef #[密码]
      port: 587
      properties:
        mail:
          smtp:
            auth: true
          starttls:
            enable: true
            required: true
mybatis:
  config-location: classpath:/mybatis.xml
  mapper-locations: classpath:/mapper/*.xml
logging:
  level: info
  file: ./log.log

